<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Cart;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function refuseProduct($cartId)
    {
        $em = $this->getEntityManager();
        $db = $em->createQueryBuilder();
        $query = $db
            ->update(Cart::class, 'c')
            ->set('c.refused', '1')
            ->where('c.id = ?1')
            ->setParameter(1, $cartId)
            ->getQuery();
        $query->execute();

    }

}
