<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Product;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoriesIds($productId)
    {
        $em = $this->getEntityManager();
        $db = $em->createQueryBuilder();
        $query = $db
            ->select('p.id')
            ->from(Product::class, 'p')
            ->join('p.categories', 'c')
            ->where('p.id = ?1')
            ->setParameter(1, $productId)
            ->getQuery();
        $categoriesIds = $query->execute();
        return $categoriesIds;
    }

    public function findByPriority()
    {
        return $this->createQueryBuilder('product')
            ->orderBy('product.priority','desc')
            ->getQuery()
            ->getResult();
    }
}
