<?php

namespace AppBundle\Repository;

/**
 * UserPurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPurchaseRepository extends \Doctrine\ORM\EntityRepository
{
}
